Update md files
perlajarillo/flad-mentorship pull request #64
Opened 2019-04-17 20:12 UTC by perlajarillo

In this branch we are updating the information about the program in the README and LICENSE files.

2019-04-17 20:13 UTC, perlajarillo commented
Related with #58

2019-04-19 10:20 UTC, Fa-v commented on LICENSE.md
>  Copyright (c) 2019 Perla Jarillo, Faviola Vieyra
*Fabiola

2019-04-19 10:31 UTC, Fa-v commented on README.md
> +This app helps to link people to participate as a mentor or a mentee in the program [Let's talk about business](https://www.flad.pt/en/lets-talk-about-business/) in coordination to the Flad-Mentorshi
*in coordination with...

2019-04-19 10:32 UTC, Fa-v commented on README.md
> +Next you will need to create a folder to storage the pictures of the mentors participating in Let's Talk About Business program.
Next, you will need to create a folder to *store...

2019-04-19 10:37 UTC, Fa-v requested changes
Hi Perla, We just need to fix some little things :)

2019-04-19 20:50 UTC, perlajarillo commented on LICENSE.md
>  Copyright (c) 2019 Perla Jarillo, Faviola Vieyra
I am so sorry 🙈

2019-04-19 20:57 UTC, perlajarillo commented
I think I made all the requested changes, do you see something else we can improve @Fa-v ?

2019-04-21 16:51 UTC, Fa-v commented on LICENSE.md
>  Copyright (c) 2019 Perla Jarillo, Faviola Vieyra
Don't worry :)

2019-04-21 16:53 UTC, Fa-v approved these changes

2019-04-21 16:53 UTC, merged